# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"exercise1": "01_bogacz.ipynb"}

modules = ["bogacz.py"]

doc_url = "https://ImAKappa.github.io/activeinference/"

git_url = "https://github.com/ImAKappa/activeinference/tree/main/"

def custom_doc_links(name): return None
