# AUTOGENERATED! DO NOT EDIT! File to edit: 01_bogacz.ipynb (unless otherwise specified).

__all__ = ['exercise1']

# Cell
from typing import Callable
from collections import namedtuple
# Science & Math
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt

# Cell

def exercise1():
    # --- Hypotheses
    possible_food_sizes = np.linspace(0.01, 5.0, num=100)

    # --- Priors
    prior_food_size = dict(avg=3, variance=1) # v_p and Sigma_p
    priors = stats.norm(prior_food_size['avg'], prior_food_size['variance']).pdf(possible_food_sizes)

    # --- Data
    estimated_light_intensity = 2 # u
    noisyness_of_estimate = 1 # Sigma_u

    # --- Likelihoods
    light_intensity_likelihood = stats.norm(estimated_light_intensity, noisyness_of_estimate)
    # Remember that light_intensity(food_size) = food_size ** 2
    possible_light_intensities = possible_food_sizes ** 2
    likelihoods = light_intensity_likelihood.pdf(possible_light_intensities) # p(u | v)

    # --- Posterior
    probs_of_possible_food_sizes = likelihoods * priors / np.sum(likelihoods * priors) # p(v | u)
    # Interval width helps us convert between probability and probability densities
    hypothesis_interval_width = possible_food_sizes[1] - possible_food_sizes[0]
    prob_densities_of_possible_food_sizes = probs_of_possible_food_sizes / hypothesis_interval_width
    return possible_food_sizes, probs_of_possible_food_sizes